"""
build_demo.py — render the public demo page's audio, monitor data and metrics.

    python build_demo.py

Everything under docs/data/ is generated by this script and nothing in it is
hand-edited, so the page can never drift from what the renderer actually does.
The monitor on the page is drawn from the render's own trace for the same
reason the monitor in the app is: recomputing the geometry in the browser
would be a second implementation of it, free to disagree with the audio.

Level matching is the detail that makes the page an honest comparison. Each
variant is rendered unnormalised, loudness-matched to the untreated reference,
and then all variants are scaled by ONE common factor. Normalising each file
on its own would hand the listener a loudness difference and let them hear it
as a treatment difference.
"""

import json
import os
import shutil
import numpy as np
import soundfile as sf

import ringfield as rf

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "docs", "data")

SOFA = os.path.join(HERE, "hrtf", "mit_kemar_normal_pinna.sofa")

# One lap over the passage, which is the comparison the whole page is built
# around: a full revolution against a control that does not revolve.
PASSAGE_SECS = 20.0
LAP_DEG_PER_SEC = 360.0 / PASSAGE_SECS
N_SOURCES = 6
SEED = 1                      # held fixed: the measures' noise floor across
                              # seeds is larger than several effects here

TRACE_FPS = 20                # the monitor is smooth at 20; 60 triples the JSON

BEDS = [
    {"id": "drone", "file": "demo-drone.wav", "start": 8.0,
     "label": "Drone",
     "blurb": "A stationary harmonic drone, held constant in spectrum and "
              "level for the duration of the passage. The measurements "
              "reported below were made on this material."},
    {"id": "strings", "file": "demo-strings.wav", "start": 6.0,
     "label": "Strings",
     "blurb": "A slow modal progression with crossfaded chord changes, "
              "provided as a more musical alternative. Its spectrum varies "
              "over time, whereas the drone holds a fixed spectrum "
              "throughout."},
]


def variants(fs):
    """The running order. Each entry renders one FieldConfig, or None for dry."""
    lap = LAP_DEG_PER_SEC
    return [
        dict(
            id="dry", label="Untreated",
            short="the source material with no field applied",
            body="The bed as generated, summed to mono and presented "
                 "identically at both ears. Every variant below is derived "
                 "from this signal.",
            cfg=None),

        dict(
            id="coherent", label="Coherent ring",
            short="six sources on a rotating ring, without decorrelation",
            body="Six copies of the same signal are placed around the "
                 "listener and rotated. Because the copies are identical they "
                 "sum to a single image at the centre of the head, and "
                 "rotating them leaves the result unchanged. The case "
                 "establishes why decorrelation is applied in the variants "
                 "that follow.",
            cfg=rf.FieldConfig(n_sources=N_SOURCES, rotation_deg_per_sec=lap,
                               decorr_amount=0.0, seed=SEED)),

        dict(
            id="rotating", label="Rotating field",
            short="six decorrelated sources completing one revolution",
            body="The same ring with each source rendered mutually "
                 "incoherent, so that no individual source can be localized. "
                 "The field completes one full revolution over the twenty "
                 "seconds. Whether that revolution is audible is the question "
                 "under investigation.",
            cfg=rf.FieldConfig(n_sources=N_SOURCES, rotation_deg_per_sec=lap,
                               decorr_amount=1.0, seed=SEED)),

        dict(
            id="static", label="Static field (control)",
            short="the same field with its rotation rate set to zero",
            body="The matched control for the rotating variant. Source count, "
                 "decorrelation, random seed and spectrum are held identical, "
                 "and the rotation rate alone is set to zero. Comparison "
                 "against the rotating field is the only basis on which a "
                 "claim about motion can rest, since the objective measures "
                 "respond to diffuseness as well as to motion.",
            cfg=rf.FieldConfig(n_sources=N_SOURCES, rotation_deg_per_sec=0.0,
                               decorr_amount=1.0, seed=SEED)),

        dict(
            id="decoy", label="Static field at matched IACC",
            short="thirteen static sources scoring as the rotating field does",
            body="Thirteen static sources in place of six. The configuration "
                 "measures IACC 0.33 against the rotating field's 0.31, a "
                 "difference smaller than the 0.038 by which the measure "
                 "varies across random seeds. Two fields that differ in "
                 "whether they rotate therefore receive scores the measure "
                 "cannot separate, which is the basis for evaluating the "
                 "effect by listening rather than by measurement.",
            cfg=rf.FieldConfig(n_sources=13, rotation_deg_per_sec=0.0,
                               decorr_amount=1.0, seed=SEED)),

        dict(
            id="hotspot", label="Coherence hotspot",
            short="one coherent source circulating within a diffuse bed",
            body="The first source retains full coherence while the remaining "
                 "five are fully decorrelated, so that a localizable source "
                 "travels through a diffuse background. The configuration "
                 "corresponds most directly to the hypothesis under test.",
            cfg=rf.FieldConfig(n_sources=N_SOURCES, rotation_deg_per_sec=lap,
                               per_source_amount=[0.0] + [1.0] * (N_SOURCES - 1),
                               decorr_method="velvet", seed=SEED)),

        dict(
            id="field", label="Drifting grid",
            short="a five by five lattice translating past the listener",
            body="Twenty-five sources arranged on a rectangular lattice and "
                 "translated past the listener rather than rotated around "
                 "them. Sources wrap at the boundaries of the lattice, so the "
                 "count remains constant throughout. Distance is carried by "
                 "level, which accounts for the variation in opacity as "
                 "sources pass.",
            cfg=rf.FieldConfig(
                components=[rf.ComponentConfig(
                    lattice="cartesian", cols=5, rows=5,
                    extent_x_m=8.0, extent_y_m=8.0,
                    drift_y_mps=-0.9, drift_x_mps=0.35,
                    label="grid")],
                decorr=rf.DecorrConfig(amount=1.0, family="velvet", seed=SEED),
                seed=SEED)),

        dict(
            id="measured", label="Rotating field (measured HRTF)",
            short="the same revolution rendered through measured ears",
            body="The default head model is a rigid sphere without an outer "
                 "ear, which renders 30 degrees and 150 degrees identically "
                 "and folds a full revolution into a back-and-forth motion. "
                 "Substituting the MIT KEMAR measurement supplies front-back "
                 "information. Comparison against the rotating field isolates "
                 "the contribution of the head model, since the motion is "
                 "identical in both.",
            requires_sofa=True,
            cfg=rf.FieldConfig(n_sources=N_SOURCES, rotation_deg_per_sec=lap,
                               decorr_amount=1.0, seed=SEED,
                               hrtf_file=SOFA, hrtf_grid_step=1.0)),
    ]


def thin(trace, fs_frames_wanted=TRACE_FPS):
    """Subsample the render trace to a frame rate the monitor can use."""
    if not trace:
        return []
    dur = trace[-1]["t"] - trace[0]["t"]
    if dur <= 0:
        return trace[:1]
    want = max(2, int(dur * fs_frames_wanted))
    idx = np.linspace(0, len(trace) - 1, want).round().astype(int)
    out = []
    for i in sorted(set(idx.tolist())):
        f = trace[i]
        e = {"t": round(f["t"], 3),
             "az": [round(v, 1) for v in f["az"]],
             "amt": [round(v, 3) for v in f["amt"]]}
        if "dist" in f:
            e["dist"] = [round(v, 2) for v in f["dist"]]
            e["lvl"] = [round(v, 3) for v in f["lvl"]]
        out.append(e)
    return out


def build():
    if os.path.isdir(OUT):
        shutil.rmtree(OUT)
    os.makedirs(OUT)

    have_sofa = os.path.isfile(SOFA)
    if not have_sofa:
        print(f"note: {SOFA} not found, skipping the measured-HRTF variant")

    manifest = {"passage_secs": PASSAGE_SECS, "n_sources": N_SOURCES,
                "seed": SEED, "beds": [], "variants": []}
    rendered = {}       # (bed, variant) -> stereo float array
    peak = 0.0
    fs_out = 44100

    for bed in BEDS:
        path = os.path.join(HERE, bed["file"])
        if not os.path.isfile(path):
            raise SystemExit(f"missing {bed['file']} — run make_demo_audio.py first")
        stereo, mono, fs = rf.load_audio(path)
        fs_out = fs
        a = int(bed["start"] * fs)
        b = a + int(PASSAGE_SECS * fs)
        if b > len(mono):
            raise SystemExit(f"{bed['file']} is too short for a "
                             f"{PASSAGE_SECS:.0f}s passage at {bed['start']:.0f}s")
        seg_mono, seg_stereo = mono[a:b], stereo[a:b]
        # The untreated reference every variant is loudness-matched against.
        dry_ref = rf._dry_reference(seg_mono, seg_stereo, fs, dry_mono=True)

        manifest["beds"].append({k: bed[k] for k in ("id", "label", "blurb")})

        for v in variants(fs):
            if v.get("requires_sofa") and not have_sofa:
                continue
            key = (bed["id"], v["id"])
            trace = None
            if v["cfg"] is None:
                y = dry_ref.copy()
            else:
                trace = []
                hrtf = rf.hrtf_for(v["cfg"], fs)
                y = rf.render(seg_mono, hrtf, v["cfg"], fs,
                              normalize=False, trace=trace)
                y = rf._match_level(y, dry_ref, fs, "lufs")
            rendered[key] = (y, trace)
            peak = max(peak, float(np.max(np.abs(y))))
            print(f"  rendered {bed['id']}/{v['id']:10s} "
                  f"IACC={rf.iacc(y, fs):.3f}")

    # ONE scale for every file, so the comparison stays level-matched on disk.
    scale = (0.89 / peak) if peak > 0 else 1.0

    seen_variants = set()
    for (bed_id, var_id), (y, trace) in rendered.items():
        stem = f"{bed_id}-{var_id}"
        sf.write(os.path.join(OUT, stem + ".mp3"),
                 (y * scale).astype(np.float32), fs_out, format="MP3")
        if trace:
            with open(os.path.join(OUT, stem + ".trace.json"), "w") as f:
                json.dump(thin(trace), f, separators=(",", ":"))

    for v in variants(fs_out):
        if v.get("requires_sofa") and not have_sofa:
            continue
        if v["id"] in seen_variants:
            continue
        seen_variants.add(v["id"])
        cfg = v["cfg"]
        entry = {"id": v["id"], "label": v["label"], "short": v["short"],
                 "body": v["body"], "has_trace": cfg is not None}
        if cfg is not None:
            comps = cfg.resolved_components()
            entry["n_sources"] = cfg.total_sources()
            rot = max((c.rotation_deg_per_sec for c in comps),
                      key=abs, default=0.0)
            drift = max((float(np.hypot(c.drift_x_mps, c.drift_y_mps))
                         for c in comps), default=0.0)
            entry["rotation_deg_per_sec"] = round(rot, 2)
            entry["drift_mps"] = round(drift, 2)
            entry["lattice"] = comps[0].lattice
            entry["measured_hrtf"] = bool(cfg.hrtf_file)
            entry["distances"] = [round(float(d), 2)
                                  for d in rf.FieldGeometry(cfg).distances(0.0)]
            # One motion description, written once here, so the variant list,
            # the readout and the results table cannot disagree about whether
            # a given field moves. A drifting grid is moving even though its
            # rotation rate is zero.
            entry["moving"] = bool(rot) or drift > 0
            if rot and drift:
                entry["motion"] = f"{abs(rot):.0f} °/s with {drift:.2f} m/s"
            elif rot:
                laps = abs(rot) * PASSAGE_SECS / 360.0
                entry["motion"] = (f"{abs(rot):.0f} °/s"
                                   + (", one revolution" if abs(laps - 1) < 0.01
                                      else f", {laps:.1f} revolutions"))
            elif drift:
                entry["motion"] = f"translation at {drift:.2f} m/s"
            else:
                entry["motion"] = "none"
        else:
            entry["moving"] = False
            entry["motion"] = "none"
        # Per-bed measurements, so the page can show that the numbers do not
        # separate the rotating case from its control.
        entry["metrics"] = {}
        for bed in BEDS:
            y, _ = rendered[(bed["id"], v["id"])]
            entry["metrics"][bed["id"]] = {
                "iacc": round(float(rf.iacc(y, fs_out)), 3),
                "lufs": round(float(rf.loudness_lufs(y * scale, fs_out)), 1),
            }
        manifest["variants"].append(entry)

    with open(os.path.join(OUT, "manifest.json"), "w") as f:
        json.dump(manifest, f, indent=1)

    total = sum(os.path.getsize(os.path.join(OUT, f)) for f in os.listdir(OUT))
    print(f"\nwrote {len(os.listdir(OUT))} files to docs/data/ "
          f"({total/1e6:.1f} MB)")


if __name__ == "__main__":
    build()
