"""
build_demo.py — render the public demo page's audio, monitor data and metrics.

    python build_demo.py

Everything under docs/data/ is generated by this script and nothing in it is
hand-edited, so the page can never drift from what the renderer actually does.
The monitor on the page is drawn from the render's own trace for the same
reason the monitor in the app is: recomputing the geometry in the browser
would be a second implementation of it, free to disagree with the audio.

Level matching is the detail that makes the page an honest comparison. Each
variant is rendered unnormalised, loudness-matched to the untreated reference,
and then all variants are scaled by ONE common factor. Normalising each file
on its own would hand the listener a loudness difference and let them hear it
as a treatment difference.
"""

import json
import os
import shutil
import time
import numpy as np
import soundfile as sf

import ringfield as rf

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "docs", "data")

SOFA = os.path.join(HERE, "hrtf", "mit_kemar_normal_pinna.sofa")

PASSAGE_SECS = 20.0

# The ring below is the configuration the blind sessions in sessions/ were run
# on, rather than a minimal one assembled for the page. Nine sources at two
# metres, allpass decorrelation, and every source wandering 60 degrees at a
# quarter hertz. Sessions one and two returned "circling" at confidence 6 on
# it. A plainer six-source velvet ring with no wander is a much weaker stimulus
# and misrepresents what the instrument does.
N_SOURCES = 9
RING_RADIUS_M = 2.0
WANDER_DEG = 60.0
WANDER_HZ = 0.25

# Two rates on one ring, so a single stopped control serves both of them.
# A rate slow enough to take the whole passage to come round once is hard to
# hear as rotation at all, which is why neither of these is that slow.
SLOW_DEG_PER_SEC = 60.0
FAST_DEG_PER_SEC = 120.0
SEED = 1                      # held fixed: the measures' noise floor across
                              # seeds is larger than several effects here


def decorr(amount=1.0, per_source=None):
    """The decorrelation the sessions used, which is allpass rather than velvet."""
    return rf.DecorrConfig(amount=amount, per_source_amount=per_source,
                           family="allpass", ir_ms=30.0, phase_depth=1.0,
                           envelope="auto", seed=SEED)


def ring(rate_deg_per_sec, wander=WANDER_DEG, label="ring"):
    """One nine-source ring at the session geometry."""
    return rf.ComponentConfig(
        lattice="polar", rings=1, per_ring=N_SOURCES,
        r_near_m=RING_RADIUS_M, r_far_m=RING_RADIUS_M,
        rotation_deg_per_sec=rate_deg_per_sec,
        wander_deg=wander, wander_hz=WANDER_HZ,
        random_fraction=0.0, label=label)

TRACE_FPS = 20                # the monitor is smooth at 20; 60 triples the JSON

BEDS = [
    {"id": "drone", "file": "demo-drone.wav", "start": 8.0,
     "label": "Drone",
     "blurb": "A stationary harmonic drone, held constant in spectrum and "
              "level for the duration of the passage, which makes it the "
              "material any judgement of movement is best made on."},
    {"id": "strings", "file": "demo-strings.wav", "start": 6.0,
     "label": "Strings",
     "blurb": "A slow modal progression with crossfaded chord changes, "
              "provided as a more musical alternative. Its spectrum varies "
              "over time, whereas the drone holds a fixed spectrum "
              "throughout."},
]


def variants(fs):
    """The running order. Each entry renders one FieldConfig, or None for dry."""
    return [
        dict(
            id="dry", label="Untreated",
            short="the source material with no field applied",
            body="The bed as generated, summed to mono and presented "
                 "identically at both ears. Every variant below is derived "
                 "from this signal.",
            cfg=None),

        dict(
            id="coherent", label="Coherent ring",
            short="nine identical sources on a rotating ring",
            body="Nine copies of the same signal are placed around the "
                 "listener at two metres and rotated at 60 degrees per "
                 "second. Identical copies at opposed angles cancel toward a "
                 "single image at the centre of the head, which stays centred "
                 "as the ring turns. It measures IACC 0.95 where the same "
                 "ring decorrelated measures 0.22. Cancellation is exact for "
                 "an even ring and approximate for this one, which has an odd "
                 "count to match the sessions.",
            cfg=rf.FieldConfig(components=[ring(SLOW_DEG_PER_SEC, wander=0.0)],
                               decorr=decorr(0.0), seed=SEED)),

        dict(
            id="slow", label="Rotating field, slow",
            short="nine decorrelated sources at 60 degrees per second",
            body="The ring with each source rendered mutually incoherent, so "
                 "that no individual source can be localized, and with every "
                 "source wandering 60 degrees about its position at a quarter "
                 "hertz. The field turns at 60 degrees per second. This is "
                 "the configuration the blind sessions recorded in the "
                 "repository were run on, and the condition reported there as "
                 "circling at the top of the confidence scale.",
            cfg=rf.FieldConfig(components=[ring(SLOW_DEG_PER_SEC)],
                               decorr=decorr(1.0), seed=SEED)),

        dict(
            id="fast", label="Rotating field, fast",
            short="the same field at 120 degrees per second",
            body="The slow field with its rotation rate doubled and every "
                 "other parameter held fixed. Rate is the one variable "
                 "separating the two, so the pair indicates whether the "
                 "reported sensation tracks angular velocity.",
            cfg=rf.FieldConfig(components=[ring(FAST_DEG_PER_SEC)],
                               decorr=decorr(1.0), seed=SEED)),

        dict(
            id="static", label="Static field (control)",
            short="the same field with time stopped",
            body="The matched control for both rotating variants, made by "
                 "stopping time rather than by zeroing the rates. Every "
                 "source holds the position and the level it had, the "
                 "wandering stops along with the rotation, and the spatial "
                 "and level distribution of the field is preserved exactly. "
                 "A single render carries no evidence of motion on its own, "
                 "since the available measures respond to diffuseness as well "
                 "as to movement, so any claim about motion rests on the "
                 "comparison with this.",
            cfg=rf.FieldConfig(components=[ring(SLOW_DEG_PER_SEC).frozen()],
                               decorr=decorr(1.0), seed=SEED)),

        dict(
            id="hotspot", label="Coherence hotspot",
            short="one coherent source circulating within a diffuse bed",
            body="The first source retains full coherence while the remaining "
                 "eight are fully decorrelated, so a locatable source travels "
                 "through a background that is not. The arrangement separates "
                 "two things the other variants combine, since it allows the "
                 "listener to report where something is as well as whether "
                 "the field is turning.",
            cfg=rf.FieldConfig(
                components=[ring(SLOW_DEG_PER_SEC)],
                decorr=decorr(1.0, [0.0] + [1.0] * (N_SOURCES - 1)),
                seed=SEED)),

        dict(
            id="lateral", label="Field passing sideways",
            short="a lattice travelling left to right past the listener",
            body="Twenty-four sources on a rectangular lattice, carried past "
                 "the listener in a straight line rather than turned around "
                 "them. The rows are offset so that none of them runs through "
                 "the listener's position, which keeps the closest approach at "
                 "one metre. A source passing through the head arrives loud "
                 "and immediately locatable, which is what an earlier version "
                 "of this variant did and what the session logs describe as "
                 "nearer and farther rather than side to side. Travel is "
                 "lateral because the head model reproduces left and right "
                 "through both interaural cues while rendering front and back "
                 "identically.",
            cfg=rf.FieldConfig(
                components=[rf.ComponentConfig(
                    lattice="cartesian", cols=6, rows=4,
                    extent_x_m=24.0, extent_y_m=8.0,
                    drift_x_mps=1.0, drift_y_mps=0.0,
                    wander_deg=WANDER_DEG, wander_hz=WANDER_HZ,
                    edge_fade=0.35, label="lattice")],
                decorr=decorr(1.0), seed=SEED)),

        dict(
            id="measured", label="Rotating field (measured HRTF)",
            short="the slow field rendered through measured ears",
            body="The default head model is a rigid sphere without an outer "
                 "ear, so azimuth 30 degrees and azimuth 150 degrees produce "
                 "identical signals and a revolution folds into a "
                 "back-and-forth motion. Substituting the MIT KEMAR "
                 "measurement supplies the front-back difference. Motion is "
                 "identical to the slow field, so the pair isolates the "
                 "contribution of the head model.",
            requires_sofa=True,
            cfg=rf.FieldConfig(components=[ring(SLOW_DEG_PER_SEC)],
                               decorr=decorr(1.0), seed=SEED,
                               hrtf_file=SOFA, hrtf_grid_step=1.0)),
    ]


def thin(trace, fs_frames_wanted=TRACE_FPS):
    """Subsample the render trace to a frame rate the monitor can use."""
    if not trace:
        return []
    dur = trace[-1]["t"] - trace[0]["t"]
    if dur <= 0:
        return trace[:1]
    want = max(2, int(dur * fs_frames_wanted))
    idx = np.linspace(0, len(trace) - 1, want).round().astype(int)
    out = []
    for i in sorted(set(idx.tolist())):
        f = trace[i]
        e = {"t": round(f["t"], 3),
             "az": [round(v, 1) for v in f["az"]],
             "amt": [round(v, 3) for v in f["amt"]]}
        if "dist" in f:
            e["dist"] = [round(v, 2) for v in f["dist"]]
            e["lvl"] = [round(v, 3) for v in f["lvl"]]
        out.append(e)
    return out


def build():
    if os.path.isdir(OUT):
        shutil.rmtree(OUT)
    os.makedirs(OUT)

    have_sofa = os.path.isfile(SOFA)
    if not have_sofa:
        print(f"note: {SOFA} not found, skipping the measured-HRTF variant")

    # A build stamp the page appends to every audio and trace request. The
    # manifest itself is revalidated on load, so a rebuilt page reaches a
    # returning visitor instead of their cached copy of the previous one.
    manifest = {"passage_secs": PASSAGE_SECS, "n_sources": N_SOURCES,
                "seed": SEED, "build": int(time.time()),
                "beds": [], "variants": []}
    rendered = {}       # (bed, variant) -> stereo float array
    peak = 0.0
    fs_out = 44100

    for bed in BEDS:
        path = os.path.join(HERE, bed["file"])
        if not os.path.isfile(path):
            raise SystemExit(f"missing {bed['file']} — run make_demo_audio.py first")
        stereo, mono, fs = rf.load_audio(path)
        fs_out = fs
        a = int(bed["start"] * fs)
        b = a + int(PASSAGE_SECS * fs)
        if b > len(mono):
            raise SystemExit(f"{bed['file']} is too short for a "
                             f"{PASSAGE_SECS:.0f}s passage at {bed['start']:.0f}s")
        seg_mono, seg_stereo = mono[a:b], stereo[a:b]
        # The untreated reference every variant is loudness-matched against.
        dry_ref = rf._dry_reference(seg_mono, seg_stereo, fs, dry_mono=True)

        manifest["beds"].append({k: bed[k] for k in ("id", "label", "blurb")})

        for v in variants(fs):
            if v.get("requires_sofa") and not have_sofa:
                continue
            key = (bed["id"], v["id"])
            trace = None
            if v["cfg"] is None:
                y = dry_ref.copy()
            else:
                trace = []
                hrtf = rf.hrtf_for(v["cfg"], fs)
                y = rf.render(seg_mono, hrtf, v["cfg"], fs,
                              normalize=False, trace=trace)
                y = rf._match_level(y, dry_ref, fs, "lufs")
            rendered[key] = (y, trace)
            peak = max(peak, float(np.max(np.abs(y))))
            print(f"  rendered {bed['id']}/{v['id']:10s} "
                  f"IACC={rf.iacc(y, fs):.3f}")

    # ONE scale for every file, so the comparison stays level-matched on disk.
    scale = (0.89 / peak) if peak > 0 else 1.0

    seen_variants = set()
    for (bed_id, var_id), (y, trace) in rendered.items():
        stem = f"{bed_id}-{var_id}"
        sf.write(os.path.join(OUT, stem + ".mp3"),
                 (y * scale).astype(np.float32), fs_out, format="MP3")
        if trace:
            with open(os.path.join(OUT, stem + ".trace.json"), "w") as f:
                json.dump(thin(trace), f, separators=(",", ":"))

    for v in variants(fs_out):
        if v.get("requires_sofa") and not have_sofa:
            continue
        if v["id"] in seen_variants:
            continue
        seen_variants.add(v["id"])
        cfg = v["cfg"]
        entry = {"id": v["id"], "label": v["label"], "short": v["short"],
                 "body": v["body"], "has_trace": cfg is not None}
        if cfg is not None:
            comps = cfg.resolved_components()
            entry["n_sources"] = cfg.total_sources()
            # Scaled by time_scale, since a frozen control keeps its configured
            # rates and would otherwise report itself as moving.
            rot = max((c.rotation_deg_per_sec * c.time_scale for c in comps),
                      key=abs, default=0.0)
            drift = max((float(np.hypot(c.drift_x_mps, c.drift_y_mps))
                         * abs(c.time_scale) for c in comps), default=0.0)
            entry["rotation_deg_per_sec"] = round(rot, 2)
            entry["drift_mps"] = round(drift, 2)
            entry["lattice"] = comps[0].lattice
            if comps[0].lattice == "cartesian":
                entry["grid"] = [int(comps[0].cols), int(comps[0].rows)]
            entry["measured_hrtf"] = bool(cfg.hrtf_file)
            entry["distances"] = [round(float(d), 2)
                                  for d in rf.FieldGeometry(cfg).distances(0.0)]
            # One motion description, written once here, so the variant list,
            # the readout and the results table cannot disagree about whether
            # a given field moves. A drifting grid is moving even though its
            # rotation rate is zero.
            entry["moving"] = bool(rot) or drift > 0
            if rot and drift:
                entry["motion"] = f"{abs(rot):.0f} °/s with {drift:.2f} m/s"
            elif rot:
                laps = abs(rot) * PASSAGE_SECS / 360.0
                entry["motion"] = (f"{abs(rot):.0f} °/s"
                                   + (", one revolution" if abs(laps - 1) < 0.01
                                      else f", {laps:.1f} revolutions"))
            elif drift:
                entry["motion"] = f"translation at {drift:.2f} m/s"
            else:
                entry["motion"] = "none"
        else:
            entry["moving"] = False
            entry["motion"] = "none"
        # Per-bed measurements, so the page can show that the numbers do not
        # separate the rotating case from its control.
        entry["metrics"] = {}
        for bed in BEDS:
            y, _ = rendered[(bed["id"], v["id"])]
            entry["metrics"][bed["id"]] = {
                "iacc": round(float(rf.iacc(y, fs_out)), 3),
                "lufs": round(float(rf.loudness_lufs(y * scale, fs_out)), 1),
            }
        manifest["variants"].append(entry)

    with open(os.path.join(OUT, "manifest.json"), "w") as f:
        json.dump(manifest, f, indent=1)

    total = sum(os.path.getsize(os.path.join(OUT, f)) for f in os.listdir(OUT))
    print(f"\nwrote {len(os.listdir(OUT))} files to docs/data/ "
          f"({total/1e6:.1f} MB)")


if __name__ == "__main__":
    build()
